### ISSUE TITLE
Error dont stop upload

### ISSUE THREAD

**Issue by olezhikz** [codler/jQuery-Ajax-Upload#11]
var nesseserySettings = {
			processData : false,
			type: 'POST',
			beforeSend : function(xhr, s) {
				s.xhr = function () {
					var xhr = new window.XMLHttpRequest();
					xhr.upload.onprogress = s.onprogress.bind(this);
					xhr.upload.onabort = s.onabort.bind(this);
					xhr.upload.onerror = s.onerror.bind(this);
					xhr.upload.onload = s.onload.bind(this);
					return xhr;
				};
				s.data = fd;
				if (origSettings.beforeSend) {
					return origSettings.beforeSend.call(this, xhr, s); ///// <<<<< i fix there
				}
			}
		};

**Comment by codler** [comment]
Thanks!
