### ISSUE TITLE
Add image size

### ISSUE THREAD

**Issue by olezhikz** [codler/jQuery-Ajax-Upload#12]
d.change(function() {
            if (!this.files.length) {
                return false;
            }

```
        if (!s.data) {
            s.data = {};
        }

        s.files = this.files;
        s.data = $.ajaxUploadExtractData(s.data, $.ajaxUploadSerializeFiles(this));
```

//// Is just for me. If more time, cat multiple support
                        $(document.createElement('img')).attr('src', window.URL.createObjectURL(this.files[0]))
                            .load( function(){
                                s.files[0].width = this.width;
                                s.files[0].height = this.height;
                                //console.log(this.width,this.height);
                                $.ajaxUpload(s).promise(def);
                            });

```
    });
```

**Comment by codler** [comment]
@olezhikz I dont understand this, what's the point in setting width and height on File object? How are you able to get width and height later on?

**Comment by olezhikz** [comment]
Later , as I understand it, the file was already starting to go

**Comment by codler** [comment]
Can you show an example?
